fix: Changed From method to get the AVD name from the config.ini
unoplatform/uno.check pull request #23
Opened 2021-12-03 05:39 UTC by jguadagno

fix: Changed From method to get the AVD name from the config.ini

Reorganized the `From` method to extract the name of the AVD from the config.ini so that the *`<avd_name>.ini`* could be built.

Refs: #20

2021-12-03 05:40 UTC, jguadagno commented
@Xiaoy312 Is this one correct?

2021-12-03 05:58 UTC, Xiaoy312 requested changes
looking good, just fix these two
btw, you can use "push -f" to update the pr without having to re-create a new one

2021-12-03 05:58 UTC, Xiaoy312 commented on UnoCheck/AndroidSdk/Avd.cs
> +
remove

2021-12-03 05:58 UTC, Xiaoy312 commented on UnoCheck/AndroidSdk/Avd.cs
> +
remove

2021-12-03 13:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unoplatform/uno.check?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/unoplatform/uno.check?pullRequest=23) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jguadagno<br/>:x: JGuadagno<br/><hr/>**JGuadagno** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unoplatform/uno.check?pullRequest=23) it.</sub>

2021-12-03 18:51 UTC, agneszitte-nventive commented
@jguadagno you will need to accept the [Contributor License Agreement](https://cla-assistant.io/unoplatform/uno.check?pullRequest=23) before the PR can be merged :)

2021-12-03 20:26 UTC, jguadagno commented
@agneszitte-nventive I have.  Git is showing two jguadagno's in the commit.  One as **jguadagno** and one as **Jguadagno**

I'm looking to see if I can fix it.

2021-12-03 21:35 UTC, jguadagno commented
@agneszitte-nventive  Fixed!

2021-12-06 20:15 UTC, jguadagno commented
@Xiaoy312 Is there anything needed?

2021-12-07 11:02 UTC, davidjohnoliver approved these changes

2021-12-07 15:10 UTC, Xiaoy312 approved these changes

2021-12-07 15:11 UTC, merged